import { jsPDF } from "jspdf";

/**
 * Generates a high-fidelity incident report as a PDF.
 * @param {Object} alert - The resolved alert object.
 */
export const generateIncidentReport = (alert) => {
    const doc = new jsPDF();
    const primaryColor = [0, 242, 254]; // Brand cyan
    const darkBg = [10, 10, 10];

    // Header Segment
    doc.setFillColor(...darkBg);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(...primaryColor);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("SECURE ACCESS AI : INCIDENT REPORT", 10, 25);
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text(`TICKET ID: ${alert.id.toUpperCase()}`, 10, 35);
    doc.text(`GENERATED: ${new Date().toLocaleString()}`, 150, 35);

    // Metadata Table
    let y = 50;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("1. BASIC METADATA", 10, y);
    y += 10;
    
    const metadata = [
        ["Threat Type", alert.name],
        ["Severity", alert.severity],
        ["Visitor ID", alert.context?.visitorId || "N/A"],
        ["Location Zone", alert.context?.zone || "N/A"],
        ["Timestamp", new Date(alert.timestamp).toLocaleString()],
        ["Resolution Time", new Date(alert.resolutionTime).toLocaleString()],
        ["Detection Logic", alert.ruleId]
    ];

    doc.setFontSize(10);
    metadata.forEach(([label, value]) => {
        doc.setFont("helvetica", "bold");
        doc.text(`${label}:`, 15, y);
        doc.setFont("helvetica", "normal");
        doc.text(String(value), 60, y);
        y += 7;
    });

    // Neural Evidence Section
    y += 10;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("2. NEURAL EVIDENCE CHAIN", 10, y);
    y += 10;

    const evidence = alert.context?.evidence || ["No granular evidence recorded for this deterministic rule."];
    doc.setFontSize(9);
    doc.setFont("courier", "normal");
    evidence.forEach((line) => {
        const lines = doc.splitTextToSize(`> ${line}`, 180);
        doc.text(lines, 15, y);
        y += (lines.length * 6);
    });

    // Threat Vector Analysis
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("3. SYSTEM ACTION SUMMARY", 10, y);
    y += 10;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    
    const summary = alert.severity === 'CRITICAL' 
        ? "System triggered T-Series escalation up to Level 3. Lockout protocols were suggested but deferred to human oversight. Incident resolved by guard acknowledgement."
        : "Standard tracking event flagged by heuristic rule. Resolved within operational threshold.";
        
    const summaryLines = doc.splitTextToSize(summary, 180);
    doc.text(summaryLines, 15, y);
    y += (summaryLines.length * 7);

    // Footer
    doc.setDrawColor(200, 200, 200);
    doc.line(10, 280, 200, 280);
    doc.setFontSize(8);
    doc.text("This is an autogenerated secure document for internal facility auditing.", 10, 285);
    doc.text("SECURE ACCESS AI - (c) 2026", 170, 285);

    // Save
    doc.save(`Incident_Report_${alert.id.substr(0, 8)}.pdf`);
};
